# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{i18n_serializer}
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nicola Racco"]
  s.date = %q{2011-03-03}
  s.description = %q{Provides some helpers to simplify the use of serialization to manage database i18n management}
  s.email = %q{nicola@nicolaracco.com}
  s.files = [
    "Rakefile",
    "config/database.yml",
    "db/schema.rb",
    "lib/i18n_serializer.rb",
    "rails/init.rb",
    "spec/cases/topic.rb",
    "spec/debug.log",
    "spec/i18n_serializer_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/nicolaracco/i18n_serializer.git}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{I18n with serialize helper}
  s.test_files = [
    "spec/cases/topic.rb",
    "spec/i18n_serializer_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 2.3.8"])
      s.add_development_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_development_dependency(%q<sqlite3>, [">= 1.3.3"])
    else
      s.add_dependency(%q<rails>, [">= 2.3.8"])
      s.add_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_dependency(%q<sqlite3>, [">= 1.3.3"])
    end
  else
    s.add_dependency(%q<rails>, [">= 2.3.8"])
    s.add_dependency(%q<rspec>, [">= 2.5.0"])
    s.add_dependency(%q<sqlite3>, [">= 1.3.3"])
  end
end

